export const REGISTER_LOADING = "REGISTER_LOADING"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_ERROR = "REGISTER_ERROR"





export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_LOADING = "LOGIN_LOADING"


export const CONTACT_ERROR = "CONTACT_ERROR"
export const CONTACT_SUCCESS = "CONTACT_SUCCESS"
export const CONTACT_LOADING = "CONTACT_LOADING"


export const LOGOUT_USER = "LOGOUT_USER"

export const ADD_CONTACT_ERROR = "ADD_CONTACT_ERROR";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_LOADING = "ADD_CONTACT_LOADING";
export const ADD_CONTACT_CLEAR = "ADD_CONTACT_CLEAR";


